version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_clinic
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresStorage:/var/lib/postgresql/data
    networks:
      - postgres_network

#  backend:
#     restart: unless-stopped
#     container_name: unibot_backend
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 49100:49100
#     env_file:
#       - .env
#     environment:
#       POSTGRES_HOST: postgres
#     volumes:
#       - ./data/faiss:/src/faiss-db
#     depends_on:
#       - postgres
#     networks:
#       - postgres_network

volumes:
  postgresStorage:

networks:
  postgres_network:
    driver: bridge